.TH NOSLEEP 1 "Sep 20, 2011" "0.1" "CYGWIN"


.SH NAME
nosleep - Run a program while inhibiting computer sleep or hibernation


.SH SYNOPSIS
.B nosleep
[OPTIONS]
.I command
.RI [ args ]


.SH DESCRIPTION
.B nosleep
runs the supplied command,
.I command 
.RI [ args ],
while inhibiting the computer from sleeping or hibernating until the command
finishes executing.

.B nosleep
does not guarantee that the computer won't go to sleep.  By default, it just
prevents the computer from automatically putting itself to sleep during periods
of no user input (although it still allows the display to turn off).  If the
user closes the laptop lid or presses the power button, the computer will still
behave as its power management plan dictates--typically by sleeping,
hibernating, or shutting down.

Inhibiting idle sleep is a safe mode of operation, since it won't prevent the
computer from shutting down if needs to to conserve power, and for many
applications this mode is sufficient.  When it's not, options are available,
below, to more aggressively inhibit sleep or hibernation.  But before you use
any of them, you must read the:


.SH WARNINGS AND DISCLAIMER
Aggressively inhibiting sleep or hibernation carries at least the following
disadvantages and risks:

.TP
1.
If the host is running on battery, preventing sleep, hibernation, or display
shutoff could cause the host to run out of power and shut down uncleanly,
potentially causing data loss.

.TP
2.
Users may become confused or frustrated if the usual sleep behavior that they
expect, such as going to sleep when the laptop lid is closed, stops working or
only works some of the time.

.TP
3.
.B nosleep
still can't guarantee that the
.I command
will complete, since it can't prevent users or other processes from shutting
down the host.  For example, a user who tries and fails to put the computer to
sleep may decide to shut it down instead.

.LP
The author disclaims all responsibility for any losses you may incur by using
the more aggressive options below.


.SH OPTIONS
.TP
--awaymode
Make the computer go into "away mode" when it would normally go to sleep.
The computer will appear to be asleep, but the
.I command
will continue executing.  The Windows documentation[1] says: "Applications that
do not require critical background processing or that run on portable computers
should not enable away mode because it prevents the system from conserving power
by entering true sleep."  Use your power for good, not evil.

Away mode is only available if it's allowed by the active power plan, and there
is no direct way for the user to determine if this is the case.  For more
information see the section "Away Mode and Windows Vista Power Policy" in [2].

.I Windows Server 2003 and Windows XP/2000:
Away mode is not supported.  This option will have no effect.

.TP
--display
Prevent the display from dimming or turning off during idle periods.

.TP
--ifacpower
Options that follow this one will only take effect if the host is running on AC
power. The AC power state is only checked when
.B nosleep
starts; if AC power is removed after that,
.B nosleep
won't detect it.

.SH EXAMPLES
.IP
nosleep rsync dir1 dir2
.LP
will run rsync dir1 dir2, preventing idle sleep until rsync exits.
.IP
nosleep --ifacpower --display rsync dir1 dir2
.LP
will prevent idle sleep as before, and will also keep the display from turning
off if the computer is running on AC power when
.B nosleep
starts.

.SH RETURN VALUE
.B nosleep
returns the exit value of
.IR command ,
or 128 if it encounters a fatal error.

.SH BUGS
Please send bug reports to the Cygwin mailing list <cygwin@cygwin.com>.

.SH REFERENCES
.TP
[1]
http://msdn.microsoft.com/en-us/library/aa373208(VS.85).aspx
.TP
[2]
http://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/AwayMode.doc
.SH AUTHOR
Andrew E. Schulman <schulman.andrew@epa.gov>
